- name: include OS specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "setup-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "setup-{{ ansible_distribution }}.yml"
      - "setup-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
      - "setup-{{ ansible_os_family }}.yml"
      - "setup.yml"

- block:
  - include_tasks: build.yml
    when: pbspro_prebuild is not true
  when: pbspro_installation is true

- include_tasks: config.yml
  when: pbspro_setup is true
